<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Discord.Addons.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="SmartReader" />
    <PackageReference Include="TimeZoneNames" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Monody.Data\Monody.Data.csproj" />
    <ProjectReference Include="..\..\Monody.Services\Monody.Services.csproj" />
  </ItemGroup>

</Project>
