<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Monody.Domain\Monody.Domain.csproj" />
    <ProjectReference Include="..\Monody.AI.Tools\Monody.AI.Tools.csproj" />
  </ItemGroup>

</Project>
